import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <nav className="flex justify-center space-x-8 mt-4 bg-orange-600">
      <ul className="flex space-x-4">
      <Link href={"/"}> <li className="text-white-300 hover:text-white transition">Home</li></Link>
        <li className="text-white-300 hover:text-white cursor-pointer">Blog</li>
        <li className="text-white-300 hover:text-white transition cursor-pointer">About Us</li>    
    </ul>
      </nav>

      
        {children}
      </body>
    </html>
  );
}
